services:
  postgres:
    image: postgres:15-alpine
    container_name: techroute-postgres
    restart: unless-stopped
    ports:
    - "5434:5432"

    environment:
      POSTGRES_USER: techroute_user
      POSTGRES_PASSWORD: changeme123
      POSTGRES_DB: techroute_db
      DATABASE_URL: "postgresql://techroute_user:changeme123@postgres:5432/techroute_db?schema=public"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U techroute_user -d techroute_db"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - techroute-network

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: techroute-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    networks:
      - techroute-network

  opensearch:
    image: opensearchproject/opensearch:3
    container_name: techroute-opensearch
    restart: unless-stopped

    environment:
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
      DISABLE_SECURITY_PLUGIN: "true"

    ulimits:
      memlock:
        soft: -1
        hard: -1

    volumes:
      - opensearch-data:/usr/share/opensearch/data

    ports:
      - "9200:9200"

    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:9200 >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

    networks:
      - techroute-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    image: techroute-backend:latest
    container_name: techroute-backend

    restart: unless-stopped

    environment:
      PORT: "8082"
      DATABASE_URL: "postgresql://techroute_user:changeme123@postgres:5432/techroute_db?schema=public"
      CLIENT_URLS: "http://localhost:5173,http://127.0.0.1:5173"
      ACCESS_TOKEN_SECRET: "accesssecret123"
      REFRESH_TOKEN_SECRET: "refreshsecret123"
      MQTT_BROKER_URL: "mqtts://mosquitto:1883"

    depends_on:
      postgres:
        condition: service_healthy
      opensearch:
        condition: service_healthy

    ports:
      - "8082:8082"



    networks:
      - techroute-network

  frontend:
    build:
      context: ./megh-frontend
      dockerfile: Dockerfile

    image: techroute-frontend:latest
    container_name: techroute-frontend

    restart: unless-stopped



    ports:
      - "3000:80"

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/ >/dev/null || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

    networks:
      - techroute-network

volumes:
  postgres-data:
  opensearch-data:

networks:
  techroute-network:
    driver: bridge
